CREATE TABLE `CIM_TBL` (
  `CIM_USER_ID` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CIM_STAFF_ID` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CIM_BANK_ID` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CIM_CONM` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_COKN` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_POSTNO` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_LOCATION` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_WEB` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_TELNO` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_FAX` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_DC` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_STAFFNO` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_DIRECTORS` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_TAXCOUNSEL` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_CORPORATENO` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_TAXNO` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_CAPITAL` int DEFAULT NULL,
  `CIM_LOGWDU` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_LOCEPB` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_INFOR_SECURITY` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_DATABANK` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_FRANCHISE` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_INVOICE_NO` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_SPECIALTY` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_BUSINESSES` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CIM_RMK` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STAFF_CRD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `STAFF_CRE_DT` datetime NOT NULL,
  `CUST_UPD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `STAFF_UPD_DT` datetime NOT NULL,
  `STAFF_DELDT` datetime NOT NULL,
  PRIMARY KEY (`CIM_USER_ID`)
);

CREATE TABLE `COM_TBL` (
  `COM_ID` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `COM_CD` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `COM_CONTENT_1` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `COM_CONTENT_2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COM_CONTENT_3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COM_CRD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `COM_CRD_DT` datetime NOT NULL,
  `COM_UPD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `COM_UPD_DT` datetime NOT NULL,
  PRIMARY KEY (`COM_ID`,`COM_CD`)
);

CREATE TABLE `CUST_TBL` (
  `CUST_ID` bigint NOT NULL AUTO_INCREMENT,
  `CUST_NM` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_KN` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_PHONE` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_DELFLG` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_FAX` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_WEB` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_POSTNO` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_ADDRESS` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_TYPE` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_MONEY` bigint DEFAULT NULL,
  `CUST_INVOICE_NO` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_INFOR_SECURITY` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_DISPATCH` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_EMPNUM` int DEFAULT NULL,
  `CUST_STARTDT` datetime DEFAULT NULL,
  `CUST_ANNUALSALE` int DEFAULT NULL,
  `CUST_COMPANYREP` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_RMK1` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_RMK2` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_CLOSEDT` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_PAYDT` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_ORDERDT` int DEFAULT NULL,
  `CUST_GETDT` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_GETCDT` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_ORDERGDT` int DEFAULT NULL,
  `BANK_CD` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BANK_CHRCD` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_BANK_NM` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_BRANCH_CD` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_DEPOSITTYPE` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_ACCOUNTNO` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_NOMINEE` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CUST_CRD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_CRD_DT` datetime NOT NULL,
  `CUST_UPD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CUST_UPD_DT` datetime NOT NULL,
  PRIMARY KEY (`CUST_ID`)
);

CREATE TABLE `STAFF_TBL` (
  `STAFF_ID` bigint NOT NULL AUTO_INCREMENT,
  `STAFF_NO` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '社員番号',
  `STAFF_NM` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '社員氏名',
  `STAFF_KN` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'カナ',
  `STAFF_ALPHABET` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'アルファベット',
  `STAFF_SEX` char(2) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '性別',
  `STAFF_DELFLG` char(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' COMMENT '削除区分',
  `STAFF_COUNTRY` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '国籍',
  `STAFF_BIRTHPLACE` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '出身地',
  `STAFF_CLS` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'スタッフ区分',
  `STAFF_COMPANY` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '所属会社',
  `STAFF_POSTNO` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '郵便番号',
  `STAFF_ADDRESS` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '住所',
  `STAFF_BIRTHDT` date DEFAULT NULL COMMENT '生年月日',
  `STAFF_AGE` int DEFAULT NULL COMMENT '年齢',
  `STAFF_MAIL` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'メール',
  `STAFF_PHONENO` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '携帯電話',
  `STAFF_EMERGENCYCALL` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '緊急連絡先',
  `STAFF_NEARESTSTATION` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最寄駅',
  `STAFF_SALESSTATUS` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '営業ステータス',
  `STAFF_POST` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '役職',
  `STAFF_GROUP` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部署',
  `STAFF_MYNO` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'マイナンバー',
  `STAFF_RESIDENCECARD` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '在留カード',
  `STAFF_RESTYPE` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '在留資格',
  `STAFF_CARDENDDT` date DEFAULT NULL COMMENT '在留カード有効期限',
  `STAFF_PHOTO` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '写真URL',
  `STAFF_INSURANCENO` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '雇用保険番号',
  `STAFF_INSURANCETYPE` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '保険タイプ',
  `STAFF_RESUME` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '履歴書URL',
  `STAFF_RMK1` text COLLATE utf8mb4_unicode_ci COMMENT '備考1',
  `STAFF_RMK2` text COLLATE utf8mb4_unicode_ci COMMENT '備考2',
  `STAFF_INDT` date DEFAULT NULL COMMENT '契約日',
  `STAFF_OUTDT` date DEFAULT NULL COMMENT '退社日',
  `STAFF_CRD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作成者',
  `STAFF_CRD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `STAFF_UPD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '更新者',
  `STAFF_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`STAFF_ID`)
);

CREATE TABLE `USER_MST` (
  `USER_ID` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_NM` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_PWD` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_ROLE` tinyint DEFAULT NULL,
  `USER_MAILADDRESS` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_PW_EXPIRATION` datetime NOT NULL,
  `USER_EX_PW_DAY` datetime NOT NULL,
  `USER_DEPARTMENT` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_LOCK_FLG` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_DEL_FLG` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MANAGER_CRD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MANAGER_CRD_DT` datetime NOT NULL,
  `MANAGER_UPD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MANAGER_UPD_DT` datetime NOT NULL,
  PRIMARY KEY (`USER_ID`)
);
