CREATE TABLE `MANG_TBL` (
  `MANAGER_CD` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '担当者コード',
  `MANAGER_CHRCD` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '担当者子コード',
  `MANAGER_NM` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '担当者名',
  `MANAGER_CUST_ID` bigint NOT NULL COMMENT '取引先ID',
  `MANAGER_PNO` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '電話番号',
  `MANAGER_JOB` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '役職',
  `MANAGER_RMK` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '備考',
  `MANAGER_MAIL` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'メール',
  `MANAGER_CRD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作成者',
  `MANAGER_CRD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `MANAGER_UPD_USR` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '更新者',
  `MANAGER_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`MANAGER_CD`, `MANAGER_CHRCD`),
  KEY `IDX_MANG_CUST_ID` (`MANAGER_CUST_ID`),
  CONSTRAINT `FK_MANG_CUST`
    FOREIGN KEY (`MANAGER_CUST_ID`)
    REFERENCES `CUST_TBL` (`CUST_ID`)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
