RENAME TABLE `USER_MST` TO `USER_TBL`;

ALTER TABLE `USER_TBL`
  CHANGE COLUMN `MANAGER_CRD_USR` `USER_CRD_USR`
    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作成者',
  CHANGE COLUMN `MANAGER_CRD_DT` `USER_CRD_DT`
    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  CHANGE COLUMN `MANAGER_UPD_USR` `USER_UPD_USR`
    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '更新者',
  CHANGE COLUMN `MANAGER_UPD_DT` `USER_UPD_DT`
    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  MODIFY COLUMN `USER_ID`
    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ユーザーID',
  MODIFY COLUMN `USER_NM`
    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ユーザー名',
  MODIFY COLUMN `USER_PWD`
    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'パスワード',
  MODIFY COLUMN `USER_ROLE`
    tinyint DEFAULT NULL COMMENT '権限: 1=管理, 2=営業, 3=総務, 4=一般',
  MODIFY COLUMN `USER_MAILADDRESS`
    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'メールアドレス',
  MODIFY COLUMN `USER_PW_EXPIRATION`
    datetime NOT NULL COMMENT 'パスワード期限',
  MODIFY COLUMN `USER_EX_PW_DAY`
    datetime NOT NULL COMMENT '前回パスワード更新日',
  MODIFY COLUMN `USER_DEPARTMENT`
    varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部署',
  MODIFY COLUMN `USER_LOCK_FLG`
    char(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' COMMENT 'ロックフラグ',
  MODIFY COLUMN `USER_DEL_FLG`
    char(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  ADD KEY `IDX_USER_MAILADDRESS` (`USER_MAILADDRESS`);
