INSERT INTO `USER_TBL` (
  `USER_ID`,
  `USER_NM`,
  `USER_PWD`,
  `USER_ROLE`,
  `USER_MAILADDRESS`,
  `USER_PW_EXPIRATION`,
  `USER_EX_PW_DAY`,
  `USER_DEPARTMENT`,
  `USER_LOCK_FLG`,
  `USER_DEL_FLG`,
  `USER_CRD_USR`,
  `USER_CRD_DT`,
  `USER_UPD_USR`,
  `USER_UPD_DT`
) VALUES
  ('admin', 'システム管理者', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   1, 'admin@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   'システム管理部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('manager01', '佐藤 健太', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   1, 'manager01@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '管理部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('sales01', '鈴木 美咲', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   2, 'sales01@example.com', DATE_ADD(NOW(), INTERVAL 60 DAY), NOW(),
   '営業部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('sales02', '高橋 翔太', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   2, 'sales02@example.com', DATE_ADD(NOW(), INTERVAL 60 DAY), NOW(),
   '営業部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('sales03', '田中 彩', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   2, 'sales03@example.com', DATE_ADD(NOW(), INTERVAL 60 DAY), NOW(),
   '営業部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('sales04', '伊藤 大輔', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   2, 'sales04@example.com', DATE_ADD(NOW(), INTERVAL 60 DAY), NOW(),
   '営業部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('sales05', '渡辺 優', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   2, 'sales05@example.com', DATE_ADD(NOW(), INTERVAL 60 DAY), NOW(),
   '営業部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general01', '山本 直樹', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   3, 'general01@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '総務部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general02', '中村 愛', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   3, 'general02@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '総務部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general03', '小林 拓也', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   3, 'general03@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '総務部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general04', '加藤 玲奈', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general04@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '開発部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general05', '吉田 誠', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general05@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '開発部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general06', '松本 真由', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general06@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '開発部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general07', '井上 健一', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general07@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '品質管理部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general08', '清水 由美', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general08@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '品質管理部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general09', '林 大輔', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general09@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   'インフラ部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('general10', '斎藤 愛', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'general10@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   'インフラ部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('locked01', '山田 翔', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'locked01@example.com', DATE_ADD(NOW(), INTERVAL 30 DAY), NOW(),
   '開発部', '1', '0', 'admin', NOW(), 'admin', NOW()),
  ('expired01', '佐々木 彩', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'expired01@example.com', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 91 DAY),
   '営業部', '0', '0', 'admin', NOW(), 'admin', NOW()),
  ('deleted01', '削除済みユーザー', '$2y$10$4uwcWZcYtMV0X9.rhtMjg.wFRceykFOfwOGeimaWZ0sY3EYZQ2n7W',
   4, 'deleted01@example.com', DATE_ADD(NOW(), INTERVAL 90 DAY), NOW(),
   '総務部', '0', '1', 'admin', NOW(), 'admin', NOW());
