ALTER TABLE `USER_TBL`
  ADD CONSTRAINT `FK_USER_CRD_USR`
    FOREIGN KEY (`USER_CRD_USR`) REFERENCES `USER_TBL` (`USER_ID`)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  ADD CONSTRAINT `FK_USER_UPD_USR`
    FOREIGN KEY (`USER_UPD_USR`) REFERENCES `USER_TBL` (`USER_ID`)
    ON UPDATE CASCADE ON DELETE RESTRICT;
